### PR TITLE
Handle CORS correctly in case of HTTPException

### PR DESCRIPTION
**Pull request by kunkku**

### CODE REVIEW

**Comment by mossblaser** [comment]
Not the original committer but I've been caught out by this shortcoming and would be very glad to see this PR merged!

Essentially, any handler which raises an `HTTPException` containing its response rather than returning a web.Response will end up not having CORS headers applied. Two common cases where this might happen are when your API returns an error or when performing a redirect using `HTTPMovedPermanently`. The latter, in particular, is what the built-in `web.normalize_path_middleware` middleware does to amend URLs.

I have attached a small example application which demonstrates various scenarios where this fix would make things work: 

[why.py.zip](https://github.com/playpauseandstop/aiohttp-middlewares/files/9100612/why.py.zip)

Run the attached script and navigate to http://127.0.0.1:8080/ and try clicking the buttons to try requesting various pages from the server. (NB: In case you're not aware, all addresses 127.x.y.z point to localhost, not just 127.0.0.1, making for quite a handy CORS test!)

In this demo `/response` returns a `web.Response` as usual and will work since CORS headers will be added by the middleware.

The other endpoints will fail to return with a CORS-induced network error since CORS headers are not attached.

* `/exception` raises an `HTTPNotAcceptable`
* `/not-found/` isn't defined and the default "not found" handler in aiohttp raises an `HTTPNotFound` exception
* `/response/` and `/exception/` (note the trailing slashes) are redirected to the trailing-slash-less endpoints by the `web.normalize_path_middleware` which internally raises a `HTTPMovedPermanently`.

As such it would be super if all of the above cases were handled by the `cors_middleware`, enabling all of the above to be reachable via CORS.

**Comment by playpauseandstop** [comment]
@mossblaser 

Thanks a lot for detailed explanation!

I will prioritize to work on this during this week to have it released at PyPI early next week.

Will keep you posted!

**Review by playpauseandstop — APPROVED** [review]

**Comment by playpauseandstop** [comment]
@kunkku & @mossblaser 

I have merged changes into the `main` branch and cover the case with tests in #109.

I also attributed the fix to your names in [docs](https://aiohttp-middlewares.readthedocs.io/en/latest/usage.html#cors-middleware), but let me know if you don't want to have this attribution in public space.

In any case, I'm ready to release the fix in scope of `aiohttp-middlewares==2.1.0`, so expect version to be published very soon.

Once again thanks for the fix and your review!

**Comment by playpauseandstop** [comment]
Available at PyPI as `aiohttp-middlewares==2.1.0`

**Comment by kunkku** [comment]
Thank you very much for this middleware library and merging this PR! I appreciate the attribution in the docs.

**Comment by mossblaser** [comment]
Very happy to see this update, thanks for doing this so quickly! The attribution is very generous :).

**Pull request merged**
